services:
  configSrv1:
    image: mongo:latest
    container_name: configSrv1
    restart: always
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.18.0.10
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  configSrv2:
    image: mongo:latest
    container_name: configSrv2
    restart: always
    ports:
      - "27018:27018"
    networks:
      app-network:
        ipv4_address: 173.18.0.11
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  configSrv3:
    image: mongo:latest
    container_name:   configSrv3
    restart: always
    ports:
      - "27019:27019"
    networks:
      app-network:
        ipv4_address: 173.18.0.12
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongos_router1:
    image: mongo:latest
    container_name: mongos_router1
    restart: always
    ports:
      - "27020:27020"
    networks:
      app-network:
        ipv4_address: 173.18.0.13
    command:
      [
        "mongos",
        "--replSet",
        "mongo_router",
        "--configdb",
        "config_server/configSrv1:27017, configSrv2:27018, configSrv3:27019",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongos_router2:
    image: mongo:latest
    container_name: mongos_router2
    restart: always
    ports:
      - "27021:27021"
    networks:
      app-network:
        ipv4_address: 173.18.0.14
    command:
      [
        "mongos",
        "--replSet",
        "mongo_router",
        "--configdb",
        "config_server/configSrv1:27017, configSrv2:27018, configSrv3:27019",
        "--bind_ip_all",
        "--port",
        "27021"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongos_router3:
    image: mongo:latest
    container_name: mongos_router3
    restart: always
    ports:
      - "27022:27022"
    networks:
      app-network:
        ipv4_address: 173.18.0.15
    command:
      [
        "mongos",
        "--replSet",
        "mongo_router",
        "--configdb",
        "config_server/configSrv1:27017, configSrv2:27018, configSrv3:27019",
        "--bind_ip_all",
        "--port",
        "27022"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1-1:
    image: mongo:latest
    container_name: shard1-1
    restart: always
    ports:
      - "27023:27023"
    networks:
      app-network:
        ipv4_address: 173.18.0.16
    volumes:
      - shard1-1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27023"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1-2:
    image: mongo:latest
    container_name: shard1-2
    restart: always
    ports:
      - "27024:27024"
    networks:
      app-network:
        ipv4_address: 173.18.0.17
    volumes:
      - shard1-2-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27024"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1-3:
    image: mongo:latest
    container_name: shard1-3
    restart: always
    ports:
      - "27025:27025"
    networks:
      app-network:
        ipv4_address: 173.18.0.18
    volumes:
      - shard1-3-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27025"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2-1:
    image: mongo:latest
    container_name: shard2-1
    restart: always
    ports:
      - "27026:27026"
    networks:
      app-network:
        ipv4_address: 173.18.0.19
    volumes:
      - shard2-1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27026"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2-2:
    image: mongo:latest
    container_name: shard2-2
    restart: always
    ports:
      - "27027:27027"
    networks:
      app-network:
        ipv4_address: 173.18.0.20
    volumes:
      - shard2-2-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27027"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2-3:
    image: mongo:latest
    container_name: shard2-3
    restart: always
    ports:
      - "27028:27028"
    networks:
      app-network:
        ipv4_address: 173.18.0.21
    volumes:
      - shard2-3-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27028"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

#  shard2:
#    image: mongo:latest
#    container_name: shard2
#    restart: always
#    ports:
#      - "27018:27018"
#    networks:
#      app-network:
#        ipv4_address: 173.17.0.9
#    volumes:
#      - shard1-data:/data/db
#    command:
#      [
#        "--shardsvr",
#        "--replSet",
#        "shard1",
#        "--bind_ip_all",
#        "--port",
#        "27018"
#      ]
#    healthcheck:
#      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
#      interval: 5s
#      start_period: 10s
#
#  mongos_router2:
#    image: mongo:latest
#    container_name: mongos_router2
#    restart: always
#    ports:
#      - "27021:27021"
#    networks:
#      app-network:
#        ipv4_address: 173.18.0.14
#    command:
#      [
#        "mongos",
#        "--configdb",
#        "config_server/configSrv:27017",
#        "--bind_ip_all",
#        "--port",
#        "27020"
#      ]
#    healthcheck:
#      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
#      interval: 5s
#      start_period: 10s

#  shard1:
#    image: mongo:latest
#    container_name: shard1
#    restart: always
#    ports:
#      - "27018:27018"
#    networks:
#      app-network:
#        ipv4_address: 173.17.0.9
#    volumes:
#      - shard1-data:/data/db
#    command:
#      [
#        "--shardsvr",
#        "--replSet",
#        "shard1",
#        "--bind_ip_all",
#        "--port",
#        "27018"
#      ]
#    healthcheck:
#      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
#      interval: 5s
#      start_period: 10s

#  mongodb1:
#    container_name: mongo-sharding
#    image: dh-mirror.gitverse.ru/mongo:latest
#    volumes:
#      - mongodb1_data_container:/data/db
#
#  pymongo_api:
#    container_name: pymongo_api
#    build:
#      context: api_app
#      dockerfile: Dockerfile
#    image: kazhem/pymongo_api:1.0.0
#    depends_on:
#      - mongodb1
#    ports:
#      - 8080:8080
#    environment:
#      MONGODB_URL: "mongodb://mongodb1"
#      MONGODB_DATABASE_NAME: "somedb"


volumes:
  config-data:
  shard1-1-data:
  shard1-2-data:
  shard1-3-data:
  shard2-1-data:
  shard2-2-data:
  shard2-3-data:
#  mongodb1_data_container:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/16